version: "3.2"

services:
  sql-server-mssql:
    image: microsoft/mssql-server-linux:latest
    restart: always
    volumes:
      - mssql-server-linux-data:/var/opt/mssql/data
    ports:
      - "1428:1433"
    environment:
      SA_PASSWORD: "pdv123456"
      ACCEPT_EULA: "Y"

volumes:
  mssql-server-linux-data:
